### ISSUE TITLE
Error executing action `install` on resource 'package[["vim"]]'

### ISSUE THREAD

**Issue by Puneeth-n** [chef-cookbooks/vim#14]
==> default: Chef::Exceptions::ValidationFailed
==> default: ----------------------------------
==> default: Option package_name must be a kind of [String]!  You passed ["vim"].
==> default:
==> default:
==> default: Resource Declaration:
==> default: ---------------------
==> default: # In /tmp/vagrant-chef/68dd7b490f8a875a6617165e3ed3b2e2/cookbooks/vim/recipes/package.rb
==> default:
==> default:  29: package vim_base_pkgs
==> default:  30:
==> default:
==> default:
==> default:
==> default: Compiled Resource:
==> default: ------------------
==> default: # Declared in /tmp/vagrant-chef/68dd7b490f8a875a6617165e3ed3b2e2/cookbooks/vim/recipes/package.rb:29:in `from_file'
==> default:
==> default: package("["vim"]") do
==> default:   action :install
==> default:   retries 0
==> default:   retry_delay 2
==> default:   package_name ["vim"]
==> default:   cookbook_name :vim
==> default:   recipe_name "package"
==> default: end

**Comment by tas50** [comment]
You're seeing this error because you're using Chef client 11.  You'll need to upgrade to 12.1 or later which this cookbook requires.
