### ISSUE TITLE
Fixing source recipe for Ubuntu 12.04, Debian 7, and Centos 7.

### ISSUE THREAD

**Issue by iennae** [chef-cookbooks/vim#15]
## Description

Travis builds exposed issues with source recipe. 
https://travis-ci.org/chef-cookbooks/vim/jobs/111136468

## Chef Version
1.81s$ /opt/chefdk/embedded/bin/chef --version
Chef Development Kit Version: 0.11.2
chef-client version: 12.7.2
berks version: 4.2.0
kitchen version: 1.5.0

## Platform Version

Ubuntu 12.04
Debian 7
Centos 7

## Replication Case

kitchen converge source-ubuntu-1204
kitchen converge source-debian-7
kitchen converge source-centos-7

## Client Output

       Running handlers:
       [2016-02-23T05:35:17+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-02-23T05:35:17+00:00] ERROR: Exception handlers complete
       Chef Client failed. 2 resources updated in 44 seconds
       [2016-02-23T05:35:17+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-02-23T05:35:17+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-02-23T05:35:17+00:00] ERROR: bash[install_vim] (vim::source line 38) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
       ---- Begin output of "bash"  "/tmp/chef-script20160223-159-1uw9100" ----
       STDOUT: 
       STDERR: tar (child): bzip2: Cannot exec: No such file or directory
       tar (child): Error is not recoverable: exiting now
       tar: Child returned status 2
       tar: Error is not recoverable: exiting now
       make: *** No rule to make target `clean'.  Stop.
       ---- End output of "bash"  "/tmp/chef-script20160223-159-1uw9100" ----
       Ran "bash"  "/tmp/chef-script20160223-159-1uw9100" returned 2
       [2016-02-23T05:35:18+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> Converge failed on instance <source-ubuntu-1204>.
>>>>>> Please see .kitchen/logs/source-ubuntu-1204.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c '

### NOTE:

This issue tracker is for the vim cookbook.

**Comment by tas50** [comment]
Looks like the box you're testing on lacks bzip2 package.  That should probably get added to the source recipe for debian like systems.

**Comment by iennae** [comment]
Yeah, I just was testing out the solution and wrote up the issue while I was at it :)

**Comment by iennae** [comment]
resolved in 2.0.1. Made it default package, as the problem existed for newer rhel and older debian, and doesn't cause conflicts on newer versions.
