### ISSUE TITLE
Caught InvalidVersionConstraint. This means that a key in value_for_platform cannot be interpreted as a Chef::VersionConstraint.

### ISSUE THREAD

**Issue by kongakong** [chef-cookbooks/vim#9]
When I tried to install the vim recipe, I got this error message:

    ==> default: [2015-01-28T08:30:19+00:00] DEBUG: Found recipe package in cookbook vim
    ==> default: [2015-01-28T08:30:19+00:00] DEBUG: Caught InvalidVersionConstraint. This means that a key in value_for_platform cannot be interpreted as a Chef::VersionConstraint.
    ==> default: [2015-01-28T08:30:19+00:00] DEBUG: 'default' (Chef::Exceptions::InvalidVersionConstraint)
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/version_constraint.rb:113:in `parse'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/version_constraint.rb:36:in `initialize'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/dsl/platform_introspection.rb:79:in `new'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/dsl/platform_introspection.rb:79:in `block in match_versions'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/dsl/platform_introspection.rb:77:in `each'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/dsl/platform_introspection.rb:77:in `match_versions'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/dsl/platform_introspection.rb:54:in `value_for_node'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/dsl/platform_introspection.rb:149:in `value_for_platform'
    ==> default: /tmp/vagrant-chef/fde7703d3d9a9afc6709c47aeb2e0724/cookbooks/vim/recipes/package.rb:23:in `from_file'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `instance_eval'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `from_file'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/cookbook_version.rb:245:in `load_recipe'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/run_context.rb:169:in `load_recipe'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/run_context.rb:138:in `block in include_recipe'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/run_context.rb:137:in `each'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/run_context.rb:137:in `include_recipe'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
    ==> default: /tmp/vagrant-chef/fde7703d3d9a9afc6709c47aeb2e0724/cookbooks/vim/recipes/default.rb:21:in `from_file'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `instance_eval'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `from_file'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/cookbook_version.rb:245:in `load_recipe'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/run_context.rb:169:in `load_recipe'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:140:in `block in compile_recipes'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/run_context.rb:92:in `load'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/policy_builder/expand_node_object.rb:73:in `setup_run_context'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/client.rb:235:in `setup_run_context'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/client.rb:397:in `run'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/application.rb:261:in `block in fork_chef_client'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork_chef_client'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/application.rb:215:in `block in run_chef_client'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/application.rb:201:in `run_chef_client'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:245:in `block in interval_run_chef_client'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:234:in `loop'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:234:in `interval_run_chef_client'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:224:in `run_application'
    ==> default: /opt/chef/embedded/apps/chef/lib/chef/application.rb:58:in `run'
    ==> default: /opt/chef/embedded/apps/chef/bin/chef-solo:25:in `<top (required)>'
    ==> default: /usr/bin/chef-solo:40:in `load'
    ==> default: /usr/bin/chef-solo:40:in `<main>'

Here is the provision section of my Vagrant file:

      config.vm.provision :chef_zero do |chef|
        # Do not need to specify cookbook path
        #    because of the berkshelf plugin
        # Enable this for debug info
        chef.log_level = :debug
        chef.data_bags_path = "data_bags"
        chef.add_recipe 'apt'
        chef.add_recipe 'python'
        chef.add_recipe 'vim'
        chef.add_recipe 'git'
      end

Other information:

The package in **Berksfile**

    # encoding: utf-8
    source 'https://supermarket.getchef.com'
    cookbook "apt"
    cookbook "python", {}
    cookbook "vim", {}
    cookbook "git", {}
    cookbook "postfix", {}
    cookbook 'sensu', '~> 2.3.0'
    cookbook "uchiwa"

Chef version

    $ chef -v
    Chef Development Kit Version: 0.3.6

The vagrant plugin I am using 

    $ vagrant plugin list
    chef-zero (2.2.1)
    vagrant-aws (0.6.0)
    vagrant-berkshelf (4.0.2)
    vagrant-cachier (1.2.0)
    vagrant-chef-zero (0.7.1)
    vagrant-omnibus (1.4.1)
    vagrant-share (1.1.3, system)

My OS is OSX 10.10.1

The guest OS is "ubuntu/trusty64"

**Comment by jblaine** [comment]
Why are you specifying an empty version constraint in your Berksfile?

```
...
cookbook "vim", {}
...
```

Does it work without that?

**Comment by bplessis** [comment]
I have the same message on a few cookbook, however it only appear in debug mode and in my case doesn't seem to be so much critical (chef-client 12.1.1).

The second line of the error seem to point to the usage of the "default" string in the following construct:
vim_base_pkgs = value_for_platform(
  ["ubuntu", "debian", "arch"] => { "default" => ["vim"] },
  ["redhat", "centos", "fedora", "scientific"] => { "default" => ["vim-minimal","vim-enhanced"] },
  "default" => ["vim"]
)

**Comment by gsaslis** [comment]
i have the same issue as @bplessis ... 
Did you ever come up with a fix for this?

**Comment by iennae** [comment]
Based on the current version of the cookbook, this looks to have been resolved. Closing this issue. If you are still having problems, please do feel free to reopen.
